name: Bug report
description: Create a report to help us improve
title: "[Bug]:"
labels: []
assignees: []

body:
  - type: checkboxes
    attributes:
      label: Before submitting
      options:
        - label: I have read the [FAQ](https://github.com/sviatoslav-lebediev/anki-quizlet-importer-extended/wiki/FAQ) and confirmed my issue is not already answered.
          required: true

  - type: textarea
    attributes:
      label: Describe the bug
      description: A description of what the bug is.
    validations:
      required: true

  - type: input
    attributes:
      label: Quizlet deck URL
      description: Please include if applicable!
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional context
      description: Error from the addon window. Please include if applicable!
    validations:
      required: false
